/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as SettingsRouteImport } from './routes/_settings/route'
import { Route as IndexImport } from './routes/index'
import { Route as SettingsProfileImport } from './routes/_settings/profile'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const SettingsRouteRoute = SettingsRouteImport.update({
  id: '/_settings',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SettingsProfileRoute = SettingsProfileImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SettingsRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_settings': {
      id: '/_settings'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/_settings/profile': {
      id: '/_settings/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof SettingsProfileImport
      parentRoute: typeof SettingsRouteImport
    }
  }
}

// Create and export the route tree

interface SettingsRouteRouteChildren {
  SettingsProfileRoute: typeof SettingsProfileRoute
}

const SettingsRouteRouteChildren: SettingsRouteRouteChildren = {
  SettingsProfileRoute: SettingsProfileRoute,
}

const SettingsRouteRouteWithChildren = SettingsRouteRoute._addFileChildren(
  SettingsRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof SettingsRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/profile': typeof SettingsProfileRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof SettingsRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/profile': typeof SettingsProfileRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_settings': typeof SettingsRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_settings/profile': typeof SettingsProfileRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '' | '/login' | '/profile'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '' | '/login' | '/profile'
  id: '__root__' | '/' | '/_settings' | '/login' | '/_settings/profile'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRouteRoute: typeof SettingsRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRouteRoute: SettingsRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_settings",
        "/login"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_settings": {
      "filePath": "_settings/route.tsx",
      "children": [
        "/_settings/profile"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/_settings/profile": {
      "filePath": "_settings/profile.tsx",
      "parent": "/_settings"
    }
  }
}
ROUTE_MANIFEST_END */
