/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AppUser {
  created_at: Generated<Timestamp>;
  email: string;
  id: Generated<number>;
  password_hash: string;
  recovery_code: Buffer | null;
  username: string;
}

export interface UserSession {
  expires_at: Timestamp;
  id: string;
  user_id: number;
}

export interface DB {
  app_user: AppUser;
  user_session: UserSession;
}
