name: Cleanup Preview

on:
  delete:

# Add custom run name
run-name: "Cleanup Preview: ${{ github.event.ref }}"

jobs:
  cleanup:
    if: github.event.ref_type == 'branch'
    runs-on: ubuntu-latest
    env:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      NEON_API_KEY: ${{ secrets.NEON_API_KEY }}
    steps:
      - name: Delete Cloudflare Worker scripts
        run: |
          BRANCH="${{ github.event.ref }}"
          # Convert to lowercase and replace any non-alphanumeric chars with dashes
          WORKER_NAME="deploy-preview-$(echo "$BRANCH" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9]/-/g' | sed 's/--*/-/g' | sed 's/^-//;s/-$//')"
          
          # Debug logging
          echo "Original branch name: $BRANCH"
          echo "Generated WORKER_NAME: $WORKER_NAME"
          echo "Will delete workers:"
          echo "- ${WORKER_NAME}-web"
          echo "- ${WORKER_NAME}-api"
          
          # Delete web worker
          curl -s -X DELETE \
            "https://api.cloudflare.com/client/v4/accounts/${CLOUDFLARE_ACCOUNT_ID}/workers/scripts/${WORKER_NAME}-web" \
            -H "Authorization: Bearer ${CLOUDFLARE_API_TOKEN}" \
            -H "Content-Type: application/json"
            
          # Delete API worker
          curl -s -X DELETE \
            "https://api.cloudflare.com/client/v4/accounts/${CLOUDFLARE_ACCOUNT_ID}/workers/scripts/${WORKER_NAME}-api" \
            -H "Authorization: Bearer ${CLOUDFLARE_API_TOKEN}" \
            -H "Content-Type: application/json"

      - name: Setup Neon CLI
        run: npm i -g neonctl@v2

      - name: Check and Delete Neon Database Branch
        run: |
          BRANCH="${{ github.event.ref }}"
          DB_BRANCH="deploy-preview-$BRANCH"
          # List all branches and check if our branch exists
          if neonctl branches list --project-id ${{ secrets.NEON_PROJECT_ID }} --api-key "${{ secrets.NEON_API_KEY }}" | grep -q "$DB_BRANCH"; then
            echo "Deleting Neon database branch: $DB_BRANCH"
            neonctl branches delete --project-id ${{ secrets.NEON_PROJECT_ID }} --branch "$DB_BRANCH" --api-key "${{ secrets.NEON_API_KEY }}"
          else
            echo "Branch $DB_BRANCH not found in Neon database, skipping deletion"
          fi
