# .github/workflows/preview-deploy.yml
# Required GitHub Secrets and Cloudflare API Token permissions:
#   - Secrets: CLOUDFLARE_API_TOKEN, CLOUDFLARE_ACCOUNT_ID, NEON_API_KEY
#   - CLOUDFLARE_API_TOKEN must have User→Read, Workers Scripts→Write, Workers Services→Write, Workers Routes→Edit
# Triggers on PRs to main, and on branch deletions
name: Deploy Preview

on:
  pull_request:
    branches:
      - main
  delete:

jobs:
  preview:
    runs-on: ubuntu-latest
    env:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Check for API changes
        id: api_changes
        run: |
          git fetch origin main
          if git diff --quiet origin/main...HEAD -- apps/api/; then
            echo "hasApiChanges=false" >> $GITHUB_OUTPUT
          else
            echo "hasApiChanges=true" >> $GITHUB_OUTPUT
          fi

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install Wrangler
        run: npm install -g wrangler@4.10.0

      - name: Generate environment name
        id: generate_env_name
        if: steps.api_changes.outputs.hasApiChanges == 'true'
        run: |
          ENV_NAME=$(echo "${{ github.head_ref }}" | sed 's/[^a-zA-Z0-9-]/-/g')
          echo "ENV_NAME=$ENV_NAME" >> $GITHUB_OUTPUT

      - name: Deploy API preview (raw CLI)
        if: steps.api_changes.outputs.hasApiChanges == 'true'
        env:
          ENV_NAME: ${{ steps.generate_env_name.outputs.ENV_NAME }}
        run: |
          cd apps/api
          wrangler deploy --name="${ENV_NAME}"

      - name: Create Neon Database Branch for Preview
        id: create_db_branch
        if: steps.api_changes.outputs.hasApiChanges == 'true'
        uses: neondatabase/create-branch-action@v5
        with:
          project_id: 'super-waterfall-86281505'
          branch_name: ${{ steps.generate_env_name.outputs.ENV_NAME }}
          parent: 'production'
          username: 'neondb_owner'
          api_key: ${{ secrets.NEON_API_KEY }}

      - name: Push preview secrets
        if: steps.api_changes.outputs.hasApiChanges == 'true'
        env:
          ENV_NAME: ${{ steps.generate_env_name.outputs.ENV_NAME }}
        run: |
          echo "${{ steps.create_db_branch.outputs.db_url }}" \
            | wrangler secret put DATABASE_URL --name "$ENV_NAME"
          echo "development" \
            | wrangler secret put NODE_ENV --name "$ENV_NAME"

      - name: Set default API URL
        if: steps.api_changes.outputs.hasApiChanges == 'false'
        run: |
          echo "PREVIEW_API_URL=https://gefakit-api-production.fandridis.workers.dev" >> $GITHUB_ENV

      - name: Build web with preview API URL
        env:
          API_URL: ${{ env.PREVIEW_API_URL }}
        run: |
          cd apps/web
          npm run build:development

      - name: Deploy web preview
        run: |
          cd apps/web
          npm run deploy:development

  cleanup:
    if: github.event_name == 'delete' && github.event.ref_type == 'branch'
    runs-on: ubuntu-latest
    env:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      NEON_API_KEY:          ${{ secrets.NEON_API_KEY }}
    steps:
      - name: Delete Cloudflare Worker script
        run: |
          BRANCH="${{ github.event.ref }}"
          echo "Deleting Worker script for branch: $BRANCH"
          curl -s -X DELETE \
            "https://api.cloudflare.com/client/v4/accounts/${CLOUDFLARE_ACCOUNT_ID}/workers/scripts/${BRANCH}" \
            -H "Authorization: Bearer ${CLOUDFLARE_API_TOKEN}" \
            -H "Content-Type: application/json"

      - name: Delete Neon Database Branch
        uses: neondatabase/delete-branch-action@v5
        with:
          project_id: 'super-waterfall-86281505'
          branch_name: ${{ github.event.ref }}
          api_key: ${{ secrets.NEON_API_KEY }}
