# .github/workflows/preview-deploy.yml
# Triggers on pull requests to main
# Deploys API preview, captures its URL, then builds & deploys web preview with that URL
name: Deploy Preview

on:
  pull_request:
    branches:
      - main

jobs:
  preview:
    runs-on: ubuntu-latest
    env:
      # Cloudflare credentials stored in repo secrets
      CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
      CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Or your desired Node.js version

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        # This will install all dependencies, including wrangler if it's in package.json
        run: pnpm install --frozen-lockfile # Assumes you have a pnpm-lock.yaml

      - name: Deploy API preview
        id: deploy-api
        run: |
          # Change directory to the API worker package so Wrangler can find its config
          cd apps/api

          # Uploads a new version using npx wrangler
          # It prints the preview URL to stdout.
          # We capture the output and extract the URL using grep.
          # Adjust the grep pattern if your preview URL structure is different
          PREVIEW_API_URL=$(npx wrangler versions upload \ # <--- Changed wrangler to npx wrangler
            --name gefakit-api-production \
            --env preview \
          | grep -o 'https://[a-f0-9-]+-gefakit-api-production\.fandridis\.workers\.dev') # Ensure this regex matches your URL exactly

          echo "PREVIEW_API_URL=$PREVIEW_API_URL" >> $GITHUB_ENV

      - name: Build web with preview API URL
        # Ensure your frontend build process uses the API_URL environment variable
        env:
          API_URL: ${{ env.PREVIEW_API_URL }}
        run: |
          cd packages/web # Adjust path if necessary
          pnpm run build

      - name: Deploy web preview
        run: |
          cd packages/web # Adjust path if necessary
          # Wrangler will pick up the necessary info from wrangler.toml/jsonc in the packages/web directory
          npx wrangler deploy \ # <--- Changed wrangler to npx wrangler
            --name gefakit-web-production \
            --env preview