name: Deploy Preview

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

# Add permissions block
permissions:
  contents: read
  pull-requests: write

# Add custom run name
run-name: "Deploy Preview: ${{ github.head_ref }}"

jobs:
  preview:
    runs-on: ubuntu-latest
    env:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Check for API changes
        id: api_changes
        run: |
          git fetch origin main
          if git diff --quiet origin/main...HEAD -- apps/api/; then
            echo "hasApiChanges=false" >> $GITHUB_OUTPUT
          else
            echo "hasApiChanges=true" >> $GITHUB_OUTPUT
          fi

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install Wrangler
        run: npm install -g wrangler@4.10.0

      - name: Generate environment name
        id: generate_env_name
        if: steps.api_changes.outputs.hasApiChanges == 'true'
        run: |
          ENV_NAME=$(echo "${{ github.head_ref }}" | sed 's/[^a-zA-Z0-9-]/-/g')
          echo "ENV_NAME=$ENV_NAME" >> $GITHUB_OUTPUT
          echo "DB_BRANCH_NAME=deploy-preview-$ENV_NAME" >> $GITHUB_OUTPUT

      - name: Create Neon Database Branch for Preview
        if: steps.api_changes.outputs.hasApiChanges == 'true'
        id: create_db_branch
        uses: neondatabase/create-branch-action@v5
        with:
          project_id: ${{ secrets.NEON_PROJECT_ID }}
          branch_name: ${{ steps.generate_env_name.outputs.DB_BRANCH_NAME }}
          parent: 'production'
          username: 'neondb_owner'
          api_key: ${{ secrets.NEON_API_KEY }}

      - name: Deploy API preview (raw CLI)
        if: steps.api_changes.outputs.hasApiChanges == 'true'
        env:
          ENV_NAME: ${{ steps.generate_env_name.outputs.ENV_NAME }}
        run: |
          cd apps/api
          wrangler deploy --name="${ENV_NAME}-api" --var APP_URL:"https://${ENV_NAME}-web.fandridis.workers.dev"

      - name: Push preview secrets
        if: steps.api_changes.outputs.hasApiChanges == 'true'
        env:
          ENV_NAME: ${{ steps.generate_env_name.outputs.ENV_NAME }}
        run: |
          DB_URL="${{ steps.create_db_branch.outputs.db_url }}"

          # Fallback only if for some reason it's empty
          if [ -z "$DB_URL" ]; then
            DB_URL=$(
              curl -s -H "Authorization: Bearer ${{ secrets.NEON_API_KEY }}" \
                https://console.neon.tech/api/v2/projects/${{ secrets.NEON_PROJECT_ID }}/branches/${ENV_NAME} \
              | jq -r '.connectionString'
            )
          fi

          echo "$DB_URL" | wrangler secret put DATABASE_URL --name "${ENV_NAME}-api"
          echo "$DB_URL" | wrangler secret put TEST_DATABASE_URL --name "${ENV_NAME}-api"
          echo "development" | wrangler secret put NODE_ENV --name "${ENV_NAME}-api"

          echo "DATABASE_URL=$DB_URL"      >> $GITHUB_ENV
          echo "TEST_DATABASE_URL=$DB_URL" >> $GITHUB_ENV
          echo "NODE_ENV=test"             >> $GITHUB_ENV

      - name: Debug DB_URL
        if: steps.api_changes.outputs.hasApiChanges == 'true'
        run: echo "› DATABASE_URL is now → $DATABASE_URL"
          
      - name: Run API tests
        if: steps.api_changes.outputs.hasApiChanges == 'true'
        env:
          DATABASE_URL:      ${{ env.DATABASE_URL }}
          TEST_DATABASE_URL: ${{ env.TEST_DATABASE_URL }}
          NODE_ENV:          ${{ env.NODE_ENV }}
          NEON_API_KEY:      ${{ secrets.NEON_API_KEY }}
          NEON_PROJECT_ID:   ${{ secrets.NEON_PROJECT_ID }}
          APP_URL:           ${{ steps.api_changes.outputs.hasApiChanges == 'true' && format('https://{0}-web.fandridis.workers.dev', steps.generate_env_name.outputs.ENV_NAME) || env.PREVIEW_API_URL }}
        run: |
          cd apps/api
          npm run test

      - name: Set default API URL
        if: steps.api_changes.outputs.hasApiChanges == 'false'
        run: |
          echo "PREVIEW_API_URL=https://gefakit-api-production.fandridis.workers.dev" >> $GITHUB_ENV

      - name: Build web with preview API URL
        env:
          API_URL: ${{ steps.api_changes.outputs.hasApiChanges == 'true' && format('https://{0}-api.fandridis.workers.dev', steps.generate_env_name.outputs.ENV_NAME) || env.PREVIEW_API_URL }}
          VITE_API_URL: ${{ steps.api_changes.outputs.hasApiChanges == 'true' && format('https://{0}-api.fandridis.workers.dev', steps.generate_env_name.outputs.ENV_NAME) || env.PREVIEW_API_URL }}
          CLOUDFLARE_ENV: development
          VITE_NODE_ENV: development
        run: |
          cd apps/web
          npm run build:development

      - name: Deploy web preview
        env:
          ENV_NAME: ${{ steps.generate_env_name.outputs.ENV_NAME }}
        run: |
          cd apps/web
          # Deploy the web worker
          wrangler deploy --name="${ENV_NAME}-web"

      - name: Comment PR with preview URLs
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const envName = '${{ steps.generate_env_name.outputs.ENV_NAME }}';
            const hasApiChanges = '${{ steps.api_changes.outputs.hasApiChanges }}' === 'true';
            const webUrl = `https://${envName}-web.fandridis.workers.dev`;
            
            let message = `## 🚀 Preview Deployment\n\n` +
              `Latest commit: ${context.payload.head_commit.message}\n\n` +
              `Your changes have been deployed to preview environments:\n\n` +
              `- Web: ${webUrl}\n`;
            
            if (hasApiChanges) {
              const apiUrl = `https://${envName}-api.fandridis.workers.dev`;
              message += `- API: ${apiUrl}\n`;
            }
            
            message += `\nThese previews will be automatically deleted when the PR is closed.`;
            
            // Find existing comment
            const comments = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number
            });
            
            const botComment = comments.data.find(comment => 
              comment.user.login === 'github-actions[bot]' && 
              comment.body.startsWith('## 🚀 Preview Deployment')
            );
            
            if (botComment) {
              // Update existing comment
              await github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: botComment.id,
                body: message
              });
            } else {
              // Create new comment if none exists
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: message
              });
            }