name: Deploy to Cloudflare Pages

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install pnpm
        run: |
          echo "Installing pnpm..."
          npm install -g pnpm
          echo "pnpm installation complete."

      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          pnpm install --frozen-lockfile
          echo "Dependency installation complete."

      - name: Build web app
        working-directory: apps/web
        run: |
          echo "Building web app..."
          CLOUDFLARE_ENV=gefa tsc -b
          vite build
          echo "Web app build complete."

      - name: Deploy to Cloudflare Pages
        working-directory: apps/web
        run: |
          echo "Deploying to Cloudflare Pages..."
          npx wrangler deploy --no-open
          echo "Deployment to Cloudflare Pages complete."
        env:
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_PROJECT_NAME: ${{ secrets.CLOUDFLARE_PROJECT_NAME }} # Added project name
